INSERT INTO INSERT_REQUEST_ENTITY(ID,SCHEDULE_DATE, STATUS, STATUS_CODE,START_DATE,END_DATE,FILE_NAME,SUMMARY,SUCCESS_LOG_PATH,ERROR_LOG_PATH,TOTAL_LINES, SUCCESS_LINES, ERROR_LINES)
VALUES (1, '2025-06-15 12:30:24', 'NOT_STARTED', null, null, null,'filename1', null, null,null,5, 0,0);
INSERT INTO INSERT_REQUEST_ENTITY(ID,SCHEDULE_DATE, STATUS, STATUS_CODE,START_DATE,END_DATE,FILE_NAME,SUMMARY,SUCCESS_LOG_PATH,ERROR_LOG_PATH,TOTAL_LINES, SUCCESS_LINES, ERROR_LINES)
VALUES (2, '2025-06-15 12:30:24', 'NOT_STARTED', null, null, null,'filename2', null, null,null,5, 0,0);
INSERT INTO INSERT_REQUEST_ENTITY(ID,SCHEDULE_DATE, STATUS, STATUS_CODE,START_DATE,END_DATE,FILE_NAME,SUMMARY,SUCCESS_LOG_PATH,ERROR_LOG_PATH,TOTAL_LINES, SUCCESS_LINES, ERROR_LINES)
VALUES (3, '2025-06-15 12:30:24', 'NOT_STARTED', null, null, null,'filename3', null, null,null,5, 0,0);
